#include <mpi.h>
#include <stdio.h>

int main()
{
  FILE *f = fopen("wmpi-handle-size.h", "w");

  if (f == NULL)
    {
      printf("Error opening wmpi-handle-size.h\n");
      exit(1);
    }

  fprintf(f, "!\n");
  fprintf(f, "!  This file is being generated by create-wmpi-handle-size.c\n");
  fprintf(f, "!  and will calculate all of the sizes of the C handle types\n");
  fprintf(f, "!  for a particular library.\n");
  fprintf(f, "!\n");
  fprintf(f, "!  WARNING: This file is LIBRARY DEPEDENT\n");
  fprintf(f, "!\n\n");

  
  fprintf(f, "integer, parameter :: LEN_MPI_COMM = %i\n", \
          sizeof(MPI_COMM_WORLD));

  MPI_Datatype datatype;
  fprintf(f, "integer, parameter :: LEN_MPI_DATATYPE = %i\n", \
          sizeof(datatype));



  return 0;
}
