!
!  This file is being generated by create-wmpi-handle-size.c
!  and will calculate all of the sizes of the C handle types
!  for a particular library.
!
!  WARNING: This file is LIBRARY DEPEDENT
!

integer, parameter :: LEN_MPI_COMM = 8
integer, parameter :: LEN_MPI_DATATYPE = 8
