!
!  This file is being generated by create-wmpi-handle-size.c
!  and will calculate all of the sizes of the C handle types
!  for a particular library.
!
!  WARNING: This file is LIBRARY DEPENDENT
!

integer, parameter :: LEN_MPI_COMM = 8
integer, parameter :: LEN_MPI_DATATYPE = 8
integer, parameter :: LEN_MPI_ERRHANDLER = 8
integer, parameter :: LEN_MPI_FILE = 8
integer, parameter :: LEN_MPI_GROUP = 8
integer, parameter :: LEN_MPI_INFO = 8
integer, parameter :: LEN_MPI_MESSAGE = 8
integer, parameter :: LEN_MPI_OP = 8
integer, parameter :: LEN_MPI_REQUEST = 8
integer, parameter :: LEN_MPI_WIN = 8
integer, parameter :: LEN_MPI_STATUS = 24
